var UserConstants = {
  USER_RECEIVED: "USER_RECEIVED",
  SESSION_CREATED: "SESSION_CREATED",
  SESSION_DESTROYED: "SESSION_DESTROYED",
  SIGNING_UP: "SIGNING_UP",
  SIGNING_IN: "SIGNING_IN",
  USER_ERRORS: "USER_ERRORS",
  SESSION_ERRORS: "SESSION_ERRORS"
};

module.exports = UserConstants;
