var UserConstants = {
  USER_RECEIVED: "USER_RECEIVED",
  SESSION_CREATED: "SESSION_CREATED",
  SESSION_DESTROYED: "SESSION_DESTROYED",
  SIGNING_UP: "SIGNING_UP",
  SIGNING_IN: "SIGNING_IN"
};

module.exports = UserConstants;
