var UserConstants = {
  USER_RECEIVED: "USER_RECEIVED",
  USERS_RECEIVED: "USERS_RECEIVED",
  SESSION_CREATED: "SESSION_CREATED",
  SESSION_DESTROYED: "SESSION_DESTROYED",
  USER_ERRORS: "USER_ERRORS",
  SESSION_ERRORS: "SESSION_ERRORS"
};

module.exports = UserConstants;
